name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start CI Tests
      run: echo Tests started for Kunena Forum
    - name: Composer install
      run: |
        echo Installing composer
        composer validate --no-check-all --strict
        composer install --no-progress --no-suggest
    - name: Codestyle check
      run: |
        echo running codestyle check
        ./vendor/bin/phpcs --config-set ignore_errors_on_exit 1
        ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
        ./vendor/bin/phpcs --extensions=php -p --standard=./vendor/kunena/codestyle/Kunena ./src
    - uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    - name: npm install
      run: |
        npm install npm@latest -g
        npm install
    - name: Docker
      run: |
        docker build -t <joomla>
        ls ./tests/www
